// apps/demo/src/components/PokemonList.vue
<template>
  <div>
    <h1>Pokemon List</h1>
    <div v-if="isFetchingPokemonList">Loading...</div>
    <div v-else-if="!pokemonList?.results?.length">No data</div>
    <ul v-else>
      <li
        v-for="pokemon in pokemonList?.results"
        :key="pokemon.name"
      >
        <a
          :href="pokemon.url"
          target="_blank"
          class="hover:underline"
        >
          {{ pokemon.name }}
        </a>
      </li>
    </ul>
  </div>
</template>

<script setup lang="ts">
import { useAuthStoreRefs } from '@apps/demo/store/auth'

const { pokemonList, isFetchingPokemonList } = useAuthStoreRefs()
</script>

// apps/demo-react/src/components/pokemon-list.tsx
import { useAuthStore } from '@apps/demo-react/stores'

export default function PokemonList() {
  const pokemonList = useAuthStore(state => state.pokemonList)
  const isFetchingPokemonList = useAuthStore(
    state => state.isFetchingPokemonList
  )

  if (isFetchingPokemonList) {
    return <div>Loading...</div>
  }

  if (!pokemonList?.results?.length) {
    return <div>No data</div>
  }

  return (
    <ul>
      {pokemonList.results.map(pokemon => (
        <li key={pokemon.name}>
          <a href={pokemon.url} target="_blank">
            {pokemon.name}
          </a>
        </li>
      ))}
    </ul>
  )
}
